services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BotiPeluquerias
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/BotiPeluquerias?serverVersion=8.0.32&charset=utf8mb4"
    volumes:
      - ./backend/public/uploads:/var/www/public/uploads
    command: >
      sh -c "until php bin/console doctrine:query:sql 'SELECT 1'; do sleep 2; done &&
             php bin/console doctrine:migrations:migrate --no-interaction &&
             php -S 0.0.0.0:8000 -t public"



  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8000

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  db_data: