nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173', 'http://localhost']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173', 'http://localhost']
            allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
            allow_credentials: true